-- Generated by awesome_vunit_vcs.gen_vhdl <version> from test_records.Link.
-- Do not edit: change the dataclasses and generate the package again.

use std.textio.all;

library awesome_vunit_vcs;
use awesome_vunit_vcs.property_pkg.all;

package records_pkg is
  -- How the link runs.
  type mode_t is (idle, fast);

  -- One lane.
  type lane_t is record
    index : integer range 0 to 7;
    enabled : boolean;
  end record;

  -- Read the example at ``path`` of a property into a :vhdl:`records_pkg.lane_t`.
  impure function get_lane(prop : property_t; path : string := "") return lane_t;
  -- The value as text, equal to vhdl_image of the Python value.
  impure function to_string(value : lane_t) return string;

  type link_modes_array_t is array (0 to 2) of mode_t;
  type link_lanes_array_t is array (0 to 3) of lane_t;

  -- Every supported field type.
  type link_t is record
    lanes_used : integer range 1 to 8;
    name : string(1 to 6);
    name_length : natural range 0 to 6;
    color : string(1 to 5);
    color_length : natural range 0 to 5;
    payload : integer_vector(0 to 11);
    payload_length : natural range 0 to 12;
    offsets : integer_vector(0 to 4);
    offsets_length : natural range 0 to 5;
    modes : link_modes_array_t;
    modes_length : natural range 0 to 3;
    lanes : link_lanes_array_t;
    lanes_length : natural range 0 to 4;
    mode : mode_t;
    primary : lane_t;
    vlan : integer range 1 to 4094;
    has_vlan : boolean;
    backup : lane_t;
    has_backup : boolean;
  end record;

  -- Read the example at ``path`` of a property into a :vhdl:`records_pkg.link_t`.
  impure function get_link(prop : property_t; path : string := "") return link_t;
  -- The value as text, equal to vhdl_image of the Python value.
  impure function to_string(value : link_t) return string;

end package;

package body records_pkg is
  function p_field(path, name : string) return string is
  begin
    if path = "" then
      return name;
    end if;
    return path & "." & name;
  end;

  function p_item(path : string; idx : natural) return string is
  begin
    return path & "(" & integer'image(idx) & ")";
  end;

  procedure p_copy(value : string; variable target : inout string; variable length : out natural) is
    alias normalized : string(1 to value'length) is value;
  begin
    for idx in normalized'range loop
      target(target'left + idx - 1) := normalized(idx);
    end loop;
    length := value'length;
  end;

  procedure p_copy(
    value : integer_vector; variable target : inout integer_vector; variable length : out natural
  ) is
    alias normalized : integer_vector(0 to value'length - 1) is value;
  begin
    for idx in normalized'range loop
      target(target'left + idx) := normalized(idx);
    end loop;
    length := value'length;
  end;

  impure function p_image(value : integer_vector; length : natural) return string is
    variable text : line;
  begin
    write(text, string'("("));
    for idx in 0 to length - 1 loop
      if idx > 0 then
        write(text, string'(", "));
      end if;
      write(text, integer'image(value(value'left + idx)));
    end loop;
    write(text, string'(")"));
    return text.all;
  end;

  impure function get_lane(prop : property_t; path : string := "") return lane_t is
    variable result : lane_t;
  begin
    result.index := get_integer(prop, p_field(path, "index"));
    result.enabled := get_boolean(prop, p_field(path, "enabled"));
    return result;
  end;

  impure function to_string(value : lane_t) return string is
    variable text : line;
  begin
    write(text, string'("("));
    write(text, string'("index => "));
    write(text, integer'image(value.index));
    write(text, string'(", enabled => "));
    write(text, boolean'image(value.enabled));
    write(text, string'(")"));
    return text.all;
  end;

  impure function get_link(prop : property_t; path : string := "") return link_t is
    variable result : link_t;
  begin
    result.lanes_used := get_integer(prop, p_field(path, "lanes_used"));
    p_copy(get_string(prop, p_field(path, "name")), result.name, result.name_length);
    p_copy(get_string(prop, p_field(path, "color")), result.color, result.color_length);
    p_copy(get_integer_vector(prop, p_field(path, "payload")), result.payload, result.payload_length);
    p_copy(get_integer_vector(prop, p_field(path, "offsets")), result.offsets, result.offsets_length);
    result.modes_length := get_length(prop, p_field(path, "modes"));
    for idx in 0 to result.modes_length - 1 loop
      result.modes(idx) := mode_t'value(get_string(prop, p_item(p_field(path, "modes"), idx)));
    end loop;
    result.lanes_length := get_length(prop, p_field(path, "lanes"));
    for idx in 0 to result.lanes_length - 1 loop
      result.lanes(idx) := get_lane(prop, p_item(p_field(path, "lanes"), idx));
    end loop;
    result.mode := mode_t'value(get_string(prop, p_field(path, "mode")));
    result.primary := get_lane(prop, p_field(path, "primary"));
    result.has_vlan := has_field(prop, p_field(path, "vlan"));
    if result.has_vlan then
      result.vlan := get_integer(prop, p_field(path, "vlan"));
    end if;
    result.has_backup := has_field(prop, p_field(path, "backup"));
    if result.has_backup then
      result.backup := get_lane(prop, p_field(path, "backup"));
    end if;
    return result;
  end;

  impure function to_string(value : link_t) return string is
    variable text : line;
  begin
    write(text, string'("("));
    write(text, string'("lanes_used => "));
    write(text, integer'image(value.lanes_used));
    write(text, string'(", name => "));
    write(text, """" & value.name(1 to value.name_length) & """");
    write(text, string'(", color => "));
    write(text, """" & value.color(1 to value.color_length) & """");
    write(text, string'(", payload => "));
    write(text, p_image(value.payload, value.payload_length));
    write(text, string'(", offsets => "));
    write(text, p_image(value.offsets, value.offsets_length));
    write(text, string'(", modes => "));
    write(text, string'("("));
    for idx in 0 to value.modes_length - 1 loop
      if idx > 0 then
        write(text, string'(", "));
      end if;
      write(text, mode_t'image(value.modes(idx)));
    end loop;
    write(text, string'(")"));
    write(text, string'(", lanes => "));
    write(text, string'("("));
    for idx in 0 to value.lanes_length - 1 loop
      if idx > 0 then
        write(text, string'(", "));
      end if;
      write(text, to_string(value.lanes(idx)));
    end loop;
    write(text, string'(")"));
    write(text, string'(", mode => "));
    write(text, mode_t'image(value.mode));
    write(text, string'(", primary => "));
    write(text, to_string(value.primary));
    write(text, string'(", vlan => "));
    if value.has_vlan then
      write(text, integer'image(value.vlan));
    else
      write(text, string'("none"));
    end if;
    write(text, string'(", backup => "));
    if value.has_backup then
      write(text, to_string(value.backup));
    else
      write(text, string'("none"));
    end if;
    write(text, string'(")"));
    return text.all;
  end;

end package body;
